apiVersion: v1
kind: Service
metadata:
  name: svc-hpa
spec:
  selector:
    app: hpa-nginx
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hpa-nginx
  template:
    metadata:
      labels:
        app: hpa-nginx
    spec:
      containers:
      - image: nginx:latest
        name: nginx-con
        resources:
          requests:   
            cpu: 10m
          limits:     
            cpu: 20m
