apiVersion: v1
kind: Pod
metadata:
  name: live-pod
  labels:
    app: live-nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    livenessProbe:
      httpGet:
        path: /test
        port: 80
      periodSeconds: 5
      initialDelaySeconds: 3
