apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-mysql
spec:
  serviceName: "mysql"
  replicas: 3
  selector:
    matchLabels:
      app: sts-mysql
  template:
    metadata:
      labels:
        app: sts-mysql
    spec:
      containers:
      - name: sts-mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
