apiVersion: v1
kind: Namespace
metadata:
  name: tom-ns
---
apiVersion: v1
kind: Service
metadata:
  name: svc-tom
  namespace: tom-ns
spec:
  type: NodePort
  selector:
    app: tom
  ports:
  - nodePort: 31000
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tom-dep
  namespace: tom-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tom
  template:
    metadata:
      name: tom-pod
      labels:
        app: tom
    spec:
      containers:
      - name: tom-con
        image: tomcat
