apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: easy-rep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: easy
  template:
    metadata:
      labels:
        app: easy
    spec:
      containers:
      - name: easy-con
        image: oolralra/easy:1

