apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-httpd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-web
  template:
    metadata:
      labels:
        app: my-web
    spec:
      containers:
      - name: my-httpd-con
        image: httpd:latest

