apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rep
spec:
  replicas: 10
  selector:
    matchLabels:
      app: my-pod
  template:
    metadata:
      labels:
        app: my-pod
    spec:
      containers:
      - name: my-con
        image: nginx:latest

