apiVersion: v1
kind: Pod
metadata:
  name: my-pod-conf
spec:
  containers:
  - name: my-container
    image: nginx
    volumeMounts:
    - name: nginx-config-vol
      mountPath: /nginx.conf
      subPath: nginx.conf
  volumes:
  - name: nginx-config-vol
    configMap:
      name: conf
      items:
      - key: nginx.conf
        path: nginx.conf 
