apiVersion: v1
kind: Pod
metadata:
  name: my-pod-env
spec:
  containers:
  - name: my-container
    image: nginx
    env:
    - name: USERNAME
      valueFrom:
        configMapKeyRef:
          name: info
          key: username
    - name: DATABASE
      valueFrom:
        configMapKeyRef:
          name: info
          key: db_host
